# Generated by Django 2.2.7 on 2020-05-11 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_business_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='post',
            new_name='port',
        ),
    ]
