# Generated by Django 2.2.7 on 2020-05-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20200511_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='port',
            field=models.IntegerField(null=True),
        ),
    ]
