# Generated by Django 2.2.7 on 2020-05-13 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20200513_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='host',
            name='port',
            field=models.IntegerField(default='33'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HostToApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aobj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Application')),
                ('hobj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Host')),
            ],
        ),
    ]
